[package]
name = "humantime"
description = """
    A human friendly format parser for std::time::Duration.
"""
license = "MIT/Apache-2.0"
readme = "README.rst"
keywords = ["time", "human", "human-friendly", "parser", "duration"]
homepage = "http://github.com/tailhook/humantime"
documentation = "http://tailhook.github.io/humantime/"
version = "1.0.0"
authors = ["paul@colomiets.name"]

[dependencies]
quick-error = "1.0.0"

[lib]
name = "humantime"
path = "src/lib.rs"

